In [4]:
import requests
import json
import pandas as pd
from sqlalchemy import create_engine

# Import Data

In [5]:
api_key = '08f03438c8b31a22e58ce3ec9f6dabf6'

appl_annual_income_statement_response = requests.get("https://financialmodelingprep.com/api/v3/income-statement/AAPL?apikey={}".format(api_key))
appl_annual_balance_sheet_statement_response = requests.get("https://financialmodelingprep.com/api/v3/balance-sheet-statement/AAPL?apikey={}".format(api_key))
appl_annual_cash_flow_statement_response = requests.get("https://financialmodelingprep.com/api/v3/cash-flow-statement/AAPL?apikey={}".format(api_key))

In [6]:
appl_annual_income_statement = appl_annual_income_statement_response.json()
appl_annual_income_statement

[{'date': '2019-09-28',
  'symbol': 'AAPL',
  'fillingDate': '2019-10-31',
  'acceptedDate': '2019-10-30 18:12:36',
  'period': 'FY',
  'revenue': 260174000000,
  'costOfRevenue': 161782000000,
  'grossProfit': 98392000000,
  'grossProfitRatio': 0.3781776810903472,
  'researchAndDevelopmentExpenses': 16217000000,
  'generalAndAdministrativeExpenses': 18245000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 1807000000,
  'operatingExpenses': 34462000000,
  'costAndExpenses': 196244000000,
  'interestExpense': 3576000000,
  'depreciationAndAmortization': 12547000000,
  'ebitda': 76477000000,
  'ebitdaratio': 0.293945590259,
  'operatingIncome': 63930000000,
  'operatingIncomeRatio': 0.245720171885,
  'totalOtherIncomeExpensesNet': 1807000000,
  'incomeBeforeTax': 65737000000,
  'incomeBeforeTaxRatio': 0.252665523842,
  'incomeTaxExpense': 10481000000,
  'netIncome': 55256000000,
  'netIncomeRatio': 0.21238094506,
  'eps': 11.97,
  'epsdiluted': 11.89,
  'weightedAverageShsOut': 4617834000,
  'weightedAverageShsOutDil': 4648913000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000032019319000119/0000320193-19-000119-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000032019319000119/a10-k20199282019.htm'},
 {'date': '2018-09-29',
  'symbol': 'AAPL',
  'fillingDate': '2018-11-05',
  'acceptedDate': '2018-11-05 08:01:40',
  'period': 'FY',
  'revenue': 265595000000,
  'costOfRevenue': 163756000000,
  'grossProfit': 101839000000,
  'grossProfitRatio': 0.38343718820007905,
  'researchAndDevelopmentExpenses': 14236000000,
  'generalAndAdministrativeExpenses': 16705000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 0.0,
  'operatingExpenses': 30941000000,
  'costAndExpenses': 194697000000,
  'interestExpense': 3240000000,
  'depreciationAndAmortization': 10903000000,
  'ebitda': 81801000000,
  'ebitdaratio': 0.307991490804,
  'operatingIncome': 70898000000,
  'operatingIncomeRatio': 0.266940266195,
  'totalOtherIncomeExpensesNet': 2005000000,
  'incomeBeforeTax': 72903000000,
  'incomeBeforeTaxRatio': 0.274489354092,
  'incomeTaxExpense': 13372000000,
  'netIncome': 59531000000,
  'netIncomeRatio': 0.224142020746,
  'eps': 12.01,
  'epsdiluted': 11.91,
  'weightedAverageShsOut': 4955377000,
  'weightedAverageShsOutDil': 5000109000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000032019318000145/0000320193-18-000145-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000032019318000145/a10-k20189292018.htm'},
 {'date': '2017-09-30',
  'symbol': 'AAPL',
  'fillingDate': '2017-11-03',
  'acceptedDate': '2017-11-03 08:01:37',
  'period': 'FY',
  'revenue': 229234000000,
  'costOfRevenue': 141048000000,
  'grossProfit': 88186000000,
  'grossProfitRatio': 0.38469860491899105,
  'researchAndDevelopmentExpenses': 11581000000,
  'generalAndAdministrativeExpenses': 15261000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 2745000000,
  'operatingExpenses': 26842000000,
  'costAndExpenses': 167890000000,
  'interestExpense': 2323000000,
  'depreciationAndAmortization': 10157000000,
  'ebitda': 71501000000,
  'ebitdaratio': 0.311912718009,
  'operatingIncome': 61344000000,
  'operatingIncomeRatio': 0.267604282087,
  'totalOtherIncomeExpensesNet': 2745000000,
  'incomeBeforeTax': 64089000000,
  'incomeBeforeTaxRatio': 0.279578945532,
  'incomeTaxExpense': 15738000000,
  'netIncome': 48351000000,
  'netIncomeRatio': 0.210924208451,
  'eps': 9.27,
  'epsdiluted': 9.21,
  'weightedAverageShsOut': 5217242000,
  'weightedAverageShsOutDil': 5251692000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000032019317000070/0000320193-17-000070-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000032019317000070/a10-k20179302017.htm'},
 {'date': '2016-09-24',
  'symbol': 'AAPL',
  'fillingDate': '2016-10-26',
  'acceptedDate': '2016-10-26 16:42:16',
  'period': 'FY',
  'revenue': 215639000000,
  'costOfRevenue': 131376000000,
  'grossProfit': 84263000000,
  'grossProfitRatio': 0.3907595564809705,
  'researchAndDevelopmentExpenses': 10045000000,
  'generalAndAdministrativeExpenses': 14194000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 1348000000,
  'operatingExpenses': 24239000000,
  'costAndExpenses': 155615000000,
  'interestExpense': 1456000000,
  'depreciationAndAmortization': 10505000000,
  'ebitda': 70529000000,
  'ebitdaratio': 0.327069778658,
  'operatingIncome': 60024000000,
  'operatingIncomeRatio': 0.278354101067,
  'totalOtherIncomeExpensesNet': 1348000000,
  'incomeBeforeTax': 61372000000,
  'incomeBeforeTaxRatio': 0.284605289396,
  'incomeTaxExpense': 15685000000,
  'netIncome': 45687000000,
  'netIncomeRatio': 0.211867983064,
  'eps': 8.35,
  'epsdiluted': 8.31,
  'weightedAverageShsOut': 5470820000,
  'weightedAverageShsOutDil': 5500281000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000162828016020309/0001628280-16-020309-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000162828016020309/a201610-k9242016.htm'},
 {'date': '2015-09-26',
  'symbol': 'AAPL',
  'fillingDate': '2015-10-28',
  'acceptedDate': '2015-10-28 16:31:09',
  'period': 'FY',
  'revenue': 233715000000,
  'costOfRevenue': 140089000000,
  'grossProfit': 93626000000,
  'grossProfitRatio': 0.4005990201741437,
  'researchAndDevelopmentExpenses': 8067000000,
  'generalAndAdministrativeExpenses': 14329000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 1285000000,
  'operatingExpenses': 22396000000,
  'costAndExpenses': 162485000000,
  'interestExpense': 733000000,
  'depreciationAndAmortization': 11257000000,
  'ebitda': 82487000000,
  'ebitdaratio': 0.35293840789,
  'operatingIncome': 71230000000,
  'operatingIncomeRatio': 0.304772907173,
  'totalOtherIncomeExpensesNet': 1285000000,
  'incomeBeforeTax': 72515000000,
  'incomeBeforeTaxRatio': 0.310271056629,
  'incomeTaxExpense': 19121000000,
  'netIncome': 53394000000,
  'netIncomeRatio': 0.228457736987,
  'eps': 9.28,
  'epsdiluted': 9.22,
  'weightedAverageShsOut': 5753421000,
  'weightedAverageShsOutDil': 5793069000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000119312515356351/0001193125-15-356351-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000119312515356351/d17062d10k.htm'},
 {'date': '2014-09-27',
  'symbol': 'AAPL',
  'fillingDate': '2014-10-27',
  'acceptedDate': '2014-10-27 17:11:55',
  'period': 'FY',
  'revenue': 182795000000,
  'costOfRevenue': 112258000000,
  'grossProfit': 70537000000,
  'grossProfitRatio': 0.3858803577778386,
  'researchAndDevelopmentExpenses': 6041000000,
  'generalAndAdministrativeExpenses': 11993000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 980000000,
  'operatingExpenses': 18034000000,
  'costAndExpenses': 130292000000,
  'interestExpense': 384000000,
  'depreciationAndAmortization': 7946000000,
  'ebitda': 60449000000,
  'ebitdaratio': 0.330692852649,
  'operatingIncome': 52503000000,
  'operatingIncomeRatio': 0.287223392325,
  'totalOtherIncomeExpensesNet': 980000000,
  'incomeBeforeTax': 53483000000,
  'incomeBeforeTaxRatio': 0.292584589294,
  'incomeTaxExpense': 13973000000,
  'netIncome': 39510000000,
  'netIncomeRatio': 0.216143767609,
  'eps': 6.49,
  'epsdiluted': 6.45,
  'weightedAverageShsOut': 6085572000,
  'weightedAverageShsOutDil': 6122663000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000119312514383437/0001193125-14-383437-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000119312514383437/d783162d10k.htm'},
 {'date': '2013-09-28',
  'symbol': 'AAPL',
  'fillingDate': '2013-10-30',
  'acceptedDate': '2013-10-29 20:38:28',
  'period': 'FY',
  'revenue': 170910000000,
  'costOfRevenue': 106606000000,
  'grossProfit': 64304000000,
  'grossProfitRatio': 0.3762448072084723,
  'researchAndDevelopmentExpenses': 4475000000,
  'generalAndAdministrativeExpenses': 10830000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 1156000000,
  'operatingExpenses': 15305000000,
  'costAndExpenses': 121911000000,
  'interestExpense': 136000000,
  'depreciationAndAmortization': 6757000000,
  'ebitda': 55756000000,
  'ebitdaratio': 0.326230179627,
  'operatingIncome': 48999000000,
  'operatingIncomeRatio': 0.286694751624,
  'totalOtherIncomeExpensesNet': 1156000000,
  'incomeBeforeTax': 50155000000,
  'incomeBeforeTaxRatio': 0.293458545433,
  'incomeTaxExpense': 13118000000,
  'netIncome': 37037000000,
  'netIncomeRatio': 0.216704698379,
  'eps': 40.03,
  'epsdiluted': 39.75,
  'weightedAverageShsOut': 925331000,
  'weightedAverageShsOutDil': 931662000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000119312513416534/0001193125-13-416534-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000119312513416534/d590790d10k.htm'},
 {'date': '2012-09-29',
  'symbol': 'AAPL',
  'fillingDate': '2012-10-31',
  'acceptedDate': '2012-10-31 17:07:19',
  'period': 'FY',
  'revenue': 156508000000,
  'costOfRevenue': 87846000000,
  'grossProfit': 68662000000,
  'grossProfitRatio': 0.4387123980882766,
  'researchAndDevelopmentExpenses': 3381000000,
  'generalAndAdministrativeExpenses': 10040000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 522000000,
  'operatingExpenses': 13421000000,
  'costAndExpenses': 101267000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 3277000000,
  'ebitda': 58518000000,
  'ebitdaratio': 0.37389781992,
  'operatingIncome': 55241000000,
  'operatingIncomeRatio': 0.35295959312,
  'totalOtherIncomeExpensesNet': 522000000,
  'incomeBeforeTax': 55763000000,
  'incomeBeforeTaxRatio': 0.356294885884,
  'incomeTaxExpense': 14030000000,
  'netIncome': 41733000000,
  'netIncomeRatio': 0.266650906024,
  'eps': 44.64,
  'epsdiluted': 44.15,
  'weightedAverageShsOut': 934818000,
  'weightedAverageShsOutDil': 945355000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000119312512444068/0001193125-12-444068-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000119312512444068/d411355d10k.htm'},
 {'date': '2011-09-24',
  'symbol': 'AAPL',
  'fillingDate': '2011-10-26',
  'acceptedDate': '2011-10-26 16:35:25',
  'period': 'FY',
  'revenue': 108249000000,
  'costOfRevenue': 64431000000,
  'grossProfit': 43818000000,
  'grossProfitRatio': 0.40478895878945764,
  'researchAndDevelopmentExpenses': 2429000000,
  'generalAndAdministrativeExpenses': 7599000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 415000000,
  'operatingExpenses': 10028000000,
  'costAndExpenses': 74459000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 1814000000,
  'ebitda': 35604000000,
  'ebitdaratio': 0.328908350193,
  'operatingIncome': 33790000000,
  'operatingIncomeRatio': 0.312150689614,
  'totalOtherIncomeExpensesNet': 415000000,
  'incomeBeforeTax': 34205000000,
  'incomeBeforeTaxRatio': 0.315984443274,
  'incomeTaxExpense': 8283000000,
  'netIncome': 25922000000,
  'netIncomeRatio': 0.239466415394,
  'eps': 28.05,
  'epsdiluted': 27.68,
  'weightedAverageShsOut': 924258000,
  'weightedAverageShsOutDil': 936645000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000119312511282113/0001193125-11-282113-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000119312511282113/d220209d10k.htm'},
 {'date': '2010-09-25',
  'symbol': 'AAPL',
  'fillingDate': '2010-10-27',
  'acceptedDate': '2010-10-27 16:36:21',
  'period': 'FY',
  'revenue': 65225000000,
  'costOfRevenue': 39541000000,
  'grossProfit': 25684000000,
  'grossProfitRatio': 0.39377539287083174,
  'researchAndDevelopmentExpenses': 1782000000,
  'generalAndAdministrativeExpenses': 5517000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 155000000,
  'operatingExpenses': 7299000000,
  'costAndExpenses': 46840000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 1027000000,
  'ebitda': 19412000000,
  'ebitdaratio': 0.297615944806,
  'operatingIncome': 18385000000,
  'operatingIncomeRatio': 0.281870448448,
  'totalOtherIncomeExpensesNet': 155000000,
  'incomeBeforeTax': 18540000000,
  'incomeBeforeTaxRatio': 0.284246837869,
  'incomeTaxExpense': 4527000000,
  'netIncome': 14013000000,
  'netIncomeRatio': 0.214840935224,
  'eps': 15.41,
  'epsdiluted': 15.15,
  'weightedAverageShsOut': 909461000,
  'weightedAverageShsOutDil': 924712000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000119312510238044/0001193125-10-238044-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000119312510238044/d10k.htm'},
 {'date': '2009-09-26',
  'symbol': 'AAPL',
  'fillingDate': '2009-10-27',
  'acceptedDate': '2009-10-27 16:18:29',
  'period': 'FY',
  'revenue': 36537000000,
  'costOfRevenue': 23397000000,
  'grossProfit': 13140000000,
  'grossProfitRatio': 0.3596354380491009,
  'researchAndDevelopmentExpenses': 1333000000,
  'generalAndAdministrativeExpenses': 4149000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 326000000,
  'operatingExpenses': 5482000000,
  'costAndExpenses': 28879000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 703000000,
  'ebitda': 8361000000,
  'ebitdaratio': 0.2288365218819279,
  'operatingIncome': 7658000000,
  'operatingIncomeRatio': 0.2095957522511427,
  'totalOtherIncomeExpensesNet': 326000000,
  'incomeBeforeTax': 7984000000,
  'incomeBeforeTaxRatio': 0.21851821441278704,
  'incomeTaxExpense': 2280000000,
  'netIncome': 5704000000,
  'netIncomeRatio': 0.15611571831294305,
  'eps': 6.39,
  'epsdiluted': 6.29,
  'weightedAverageShsOut': 893016000,
  'weightedAverageShsOutDil': 907005000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000119312509214859/0001193125-09-214859-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000119312509214859/d10k.htm'},
 {'date': '2008-09-27',
  'symbol': 'AAPL',
  'fillingDate': '2008-11-05',
  'acceptedDate': '2008-11-05 06:16:23',
  'period': 'FY',
  'revenue': 32479000000,
  'costOfRevenue': 21334000000,
  'grossProfit': 11145000000,
  'grossProfitRatio': 0.3431448012561963,
  'researchAndDevelopmentExpenses': 1109000000,
  'generalAndAdministrativeExpenses': 3761000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 620000000,
  'operatingExpenses': 4870000000,
  'costAndExpenses': 26204000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 473000000,
  'ebitda': 6748000000,
  'ebitdaratio': 0.2077650173958558,
  'operatingIncome': 6275000000,
  'operatingIncomeRatio': 0.19320176113796608,
  'totalOtherIncomeExpensesNet': 620000000,
  'incomeBeforeTax': 6895000000,
  'incomeBeforeTaxRatio': 0.21229101881215554,
  'incomeTaxExpense': 2061000000,
  'netIncome': 4834000000,
  'netIncomeRatio': 0.14883463160811602,
  'eps': 5.48,
  'epsdiluted': 5.36,
  'weightedAverageShsOut': 881592000,
  'weightedAverageShsOutDil': 902139000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000119312508224958/0001193125-08-224958-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000119312508224958/d10k.htm'},
 {'date': '2007-09-29',
  'symbol': 'AAPL',
  'fillingDate': '2007-11-15',
  'acceptedDate': '2007-11-15 16:49:37',
  'period': 'FY',
  'revenue': 24006000000,
  'costOfRevenue': 15852000000,
  'grossProfit': 8154000000,
  'grossProfitRatio': 0.33966508372906773,
  'researchAndDevelopmentExpenses': 782000000,
  'generalAndAdministrativeExpenses': 2963000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 599000000,
  'operatingExpenses': 3745000000,
  'costAndExpenses': 19597000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 317000000,
  'ebitda': 4726000000,
  'ebitdaratio': 0.1968674498042156,
  'operatingIncome': 4409000000,
  'operatingIncomeRatio': 0.1836624177289011,
  'totalOtherIncomeExpensesNet': 599000000,
  'incomeBeforeTax': 5008000000,
  'incomeBeforeTaxRatio': 0.20861451303840706,
  'incomeTaxExpense': 1512000000,
  'netIncome': 3496000000,
  'netIncomeRatio': 0.1456302591018912,
  'eps': 4.04,
  'epsdiluted': 3.93,
  'weightedAverageShsOut': 864595000,
  'weightedAverageShsOutDil': 889292000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000104746907009340/0001047469-07-009340-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000104746907009340/a2181030z10-k.htm'},
 {'date': '2006-09-30',
  'symbol': 'AAPL',
  'fillingDate': '2006-12-29',
  'acceptedDate': '2006-12-29 06:05:58',
  'period': 'FY',
  'revenue': 13931000000,
  'costOfRevenue': 9888000000,
  'grossProfit': 4043000000,
  'grossProfitRatio': 0.29021606489124974,
  'researchAndDevelopmentExpenses': 534000000,
  'generalAndAdministrativeExpenses': 1859000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 165000000,
  'operatingExpenses': 2393000000,
  'costAndExpenses': 12281000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 225000000,
  'ebitda': 1875000000,
  'ebitdaratio': 0.134591917306726,
  'operatingIncome': 1650000000,
  'operatingIncomeRatio': 0.11844088722991888,
  'totalOtherIncomeExpensesNet': 165000000,
  'incomeBeforeTax': 1815000000,
  'incomeBeforeTaxRatio': 0.13028497595291078,
  'incomeTaxExpense': 480000000,
  'netIncome': 1335000000,
  'netIncomeRatio': 0.09582944512238892,
  'eps': 1.65,
  'epsdiluted': 1.56,
  'weightedAverageShsOut': 808439000,
  'weightedAverageShsOutDil': 856780000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000110465906084288/0001104659-06-084288-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000110465906084288/a06-25759_210k.htm'},
 {'date': '2005-09-24',
  'symbol': 'AAPL',
  'fillingDate': '2005-12-01',
  'acceptedDate': '2005-11-30 21:22:48',
  'period': 'FY',
  'revenue': 13931000000,
  'costOfRevenue': 9888000000,
  'grossProfit': 4043000000,
  'grossProfitRatio': 0.29021606489124974,
  'researchAndDevelopmentExpenses': 534000000,
  'generalAndAdministrativeExpenses': 1859000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 165000000,
  'operatingExpenses': 2393000000,
  'costAndExpenses': 12281000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 179000000,
  'ebitda': 1829000000,
  'ebitdaratio': 0.13128992893546768,
  'operatingIncome': 1650000000,
  'operatingIncomeRatio': 0.11844088722991888,
  'totalOtherIncomeExpensesNet': 165000000,
  'incomeBeforeTax': 1815000000,
  'incomeBeforeTaxRatio': 0.13028497595291078,
  'incomeTaxExpense': 480000000,
  'netIncome': 1335000000,
  'netIncomeRatio': 0.09582944512238892,
  'eps': 1.65,
  'epsdiluted': 1.56,
  'weightedAverageShsOut': 808439000,
  'weightedAverageShsOutDil': 856780000,
  'link': 'https://www.sec.gov/Archives/edgar/data/320193/000110465905058421/0001104659-05-058421-index.htm',
  'finalLink': 'https://www.sec.gov/Archives/edgar/data/320193/000110465905058421/a05-20674_110k.htm'},
 {'date': '2004-09-25',
  'symbol': 'AAPL',
  'fillingDate': '2004-12-03',
  'acceptedDate': '2004-12-02 18:05:49',
  'period': 'FY',
  'revenue': 8279000000,
  'costOfRevenue': 6020000000,
  'grossProfit': 2259000000,
  'grossProfitRatio': 0.2728590409469743,
  'researchAndDevelopmentExpenses': 489000000,
  'generalAndAdministrativeExpenses': 1421000000,
  'sellingAndMarketingExpenses': 0.0,
  'otherExpenses': 23000000,
  'operatingExpenses': 1933000000,
  'costAndExpenses': 7953000000,
  'interestExpense': 0.0,
  'depreciationAndAmortization': 150000000,
  'ebitda': 476000000,
  'ebitdaratio': 0.057494866529774126,
  'operatingIncome': 326000000,
  'operatingIncomeRatio': 0.03937673632081169,
  'totalOtherIncomeExpensesNet': 53000000,
  'incomeBeforeTax': 383000000,
  'incomeBeforeTaxRatio': 0.04626162580021742,
  'incomeTaxExpense': 107000000,
  'netIncome': 276000000,
  'netIncomeRatio': 0.03333735958449088,
  'eps': 0.74,
  'epsdiluted': 0.71,
  'weightedAverageShsOut': 371590000,
  'weightedAverageShsOutDil': 387311000,

In [7]:
appl_annual_income_statement = pd.DataFrame(appl_annual_income_statement)
appl_annual_income_statement.head()

,date,symbol,fillingDate,acceptedDate,period,revenue,costOfRevenue,grossProfit,grossProfitRatio,researchAndDevelopmentExpenses,...,incomeBeforeTaxRatio,incomeTaxExpense,netIncome,netIncomeRatio,eps,epsdiluted,weightedAverageShsOut,weightedAverageShsOutDil,link,finalLink
0,2019-09-28,AAPL,2019-10-31,2019-10-30 18:12:36,FY,260174000000,161782000000,98392000000,0.378178,16217000000,...,0.252666,10481000000,55256000000,0.212381,11.97,11.89,4617834000,4648913000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
1,2018-09-29,AAPL,2018-11-05,2018-11-05 08:01:40,FY,265595000000,163756000000,101839000000,0.383437,14236000000,...,0.274489,13372000000,59531000000,0.224142,12.01,11.91,4955377000,5000109000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
2,2017-09-30,AAPL,2017-11-03,2017-11-03 08:01:37,FY,229234000000,141048000000,88186000000,0.384699,11581000000,...,0.279579,15738000000,48351000000,0.210924,9.27,9.21,5217242000,5251692000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
3,2016-09-24,AAPL,2016-10-26,2016-10-26 16:42:16,FY,215639000000,131376000000,84263000000,0.390760,10045000000,...,0.284605,15685000000,45687000000,0.211868,8.35,8.31,5470820000,5500281000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
4,2015-09-26,AAPL,2015-10-28,2015-10-28 16:31:09,FY,233715000000,140089000000,93626000000,0.400599,8067000000,...,0.310271,19121000000,53394000000,0.228458,9.28,9.22,5753421000,5793069000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...

In [8]:
income_statement_col = appl_annual_income_statement.columns.tolist()
income_statement_row = appl_annual_income_statement.shape[0]

In [9]:
appl_annual_balance_sheet_statement = appl_annual_balance_sheet_statement_response.json()
appl_annual_balance_sheet_statement = pd.DataFrame(appl_annual_balance_sheet_statement)
appl_annual_balance_sheet_statement.head()

,date,symbol,fillingDate,acceptedDate,period,cashAndCashEquivalents,shortTermInvestments,cashAndShortTermInvestments,netReceivables,inventory,...,retainedEarnings,accumulatedOtherComprehensiveIncomeLoss,othertotalStockholdersEquity,totalStockholdersEquity,totalLiabilitiesAndStockholdersEquity,totalInvestments,totalDebt,netDebt,link,finalLink
0,2019-09-28,AAPL,2019-10-31,2019-10-30 18:12:36,FY,48844000000,51713000000,100557000000,22926000000,4106000000,...,45898000000,-5.840000e+08,4.073076e+10,90488000000,338516000000,157054000000,102067000000,53223000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
1,2018-09-29,AAPL,2018-11-05,2018-11-05 08:01:40,FY,25913000000,40388000000,66301000000,23186000000,3956000000,...,70400000000,-3.454000e+09,3.544601e+10,107147000000,365725000000,211187000000,102519000000,76606000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
2,2017-09-30,AAPL,2017-11-03,2017-11-03 08:01:37,FY,20289000000,53892000000,74181000000,17874000000,4855000000,...,98330000000,-1.500000e+08,3.074080e+10,134047000000,375319000000,248606000000,103703000000,83414000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
3,2016-09-24,AAPL,2016-10-26,2016-10-26 16:42:16,FY,20484000000,46671000000,67155000000,15754000000,2132000000,...,96364000000,6.340000e+08,2.591483e+10,128249000000,321686000000,217101000000,78927000000,58443000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
4,2015-09-26,AAPL,2015-10-28,2015-10-28 16:31:09,FY,21120000000,20481000000,41601000000,16849000000,2349000000,...,92284000000,-3.450000e+08,2.183725e+10,119355000000,290479000000,184546000000,55963000000,34843000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...

In [10]:
balance_sheet_col = appl_annual_balance_sheet_statement.columns.tolist()
balance_sheet_row = appl_annual_balance_sheet_statement.shape[0]

In [11]:
appl_annual_cash_flow_statement = appl_annual_cash_flow_statement_response.json()
appl_annual_cash_flow_statement = pd.DataFrame(appl_annual_cash_flow_statement)
appl_annual_cash_flow_statement.head()

,date,symbol,fillingDate,acceptedDate,period,netIncome,depreciationAndAmortization,deferredIncomeTax,stockBasedCompensation,changeInWorkingCapital,...,netCashUsedProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow,link,finalLink
0,2019-09-28,AAPL,2019-10-31,2019-10-30 18:12:36,FY,55256000000,12547000000,-340000000,6.068000e+09,-4.140000e+09,...,-90976000000,0.0,24311000000,50224000000,25913000000,69391000000,10495000000,58896000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
1,2018-09-29,AAPL,2018-11-05,2018-11-05 08:01:40,FY,59531000000,10903000000,-32590000000,5.340000e+09,3.425000e+10,...,-87876000000,0.0,5624000000,25913000000,20289000000,77434000000,13313000000,64121000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
2,2017-09-30,AAPL,2017-11-03,2017-11-03 08:01:37,FY,48351000000,10157000000,5966000000,4.840000e+09,-5.716000e+09,...,-17347000000,0.0,-195000000,20289000000,20484000000,63598000000,12795000000,50803000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
3,2016-09-24,AAPL,2016-10-26,2016-10-26 16:42:16,FY,45687000000,10505000000,4938000000,4.210000e+09,4.840000e+08,...,-20483000000,0.0,-636000000,20484000000,21120000000,65824000000,13548000000,52276000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
4,2015-09-26,AAPL,2015-10-28,2015-10-28 16:31:09,FY,53394000000,11257000000,1382000000,3.586000e+09,1.164700e+10,...,-17716000000,0.0,7276000000,21120000000,13844000000,81266000000,11488000000,69778000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...

In [12]:
cash_flow_col = appl_annual_cash_flow_statement.columns.tolist()
cash_flow_row = appl_annual_cash_flow_statement.shape[0]

In [13]:
def get_annual_financial_statement(ticker, statement_type, api_key):
    """
    This function aims to retrieve the selected annual financial statements of a selected company
    available in Financial Modeling Prep website. Depending on availability, all years will be retrieved.

    :param ticker: (str) listed company ticker symbol
    :param statement_type: (str) type of financial statement (income-, balance-sheet- or cash-flow-statement)
    :param api_key: (str) user's api key in Financial Modeling Prep
    :return: (pandas dataframe) annual financial statements of the selected company
    """

    annual_statement_response = requests.get("https://financialmodelingprep.com/api/v3/{}/{}?apikey={}"
                                             .format(statement_type, ticker, api_key))

    if annual_statement_response.status_code == 200:
        annual_statement = annual_statement_response.json()
    else:
        print('Get annual {} failed with {}'
              .format(statement_type, annual_statement_response.status_code))

    return pd.DataFrame(annual_statement)

In [207]:
def get_company_profile_data(ticker, api_key):
    """
    This function aims to retrieve the selected company's profile data from financialmodelingprep.com like market cap,
    industry, sector, price, beta etc.

    :param ticker: (str) listed company ticker symbol
    :param api_key: (str) user's api key in financialmodelingprep.com
    :return: (pandas dataframe) profile data of the selected company
    """

    company_profile_response = requests.get("https://financialmodelingprep.com/api/v3/profile/{}?apikey={}"
                                            .format(ticker, api_key))

    if company_profile_response.status_code == 200:
        company_profile = company_profile_response.json()
    else:
        raise ValueError('Get {} company profile data failed with {}'
              .format(ticker, company_profile_response.status_code))
        
    if pd.DataFrame(company_profile).empty:
        raise ValueError('No data retrieved! Check API!')

    return pd.DataFrame(company_profile)

In [211]:
get_company_profile_data('a34', api_key)

ValueError: No data retrieved! Check API!

In [209]:
def collect_companies_data(tickers_list, api_key):
    """
    This function aims to collect all financial data from the income, balance sheet and cash flow statement of all the
    selected companies in the tickers_list and combine them into a pandas dataset.
    Companies' profile data will be collected here and will be returned as a second pandas dataset

    :param tickers_list: a list of tickers that should be collected
    :type tickers_list: list
    :param api_key: user's api key in financialmodelingprep.com
    :type api_key: str
    :return: a dataframe with financial data from the selected companies
    :rtype: pd.DataFrame
    :return: a dataframe with profile data from the selected companies
    :rtype: pd.DataFrame
    """
    
    companies_profile_data = pd.DataFrame()
    companies_financial_data = pd.DataFrame()

    try:
        for ticker in tickers_list:
            companies_profile_data = companies_profile_data.append(get_company_profile_data(ticker, api_key), ignore_index=True)
            income_statement = get_annual_financial_statement(ticker, 'income-statement', api_key)
            balance_sheet_statement = get_annual_financial_statement(ticker, 'balance-sheet-statement', api_key)
            cash_flow_statement = get_annual_financial_statement(ticker, 'cash-flow-statement', api_key)
            financial_data = pd.concat([income_statement, balance_sheet_statement, cash_flow_statement], axis=1)
            companies_financial_data = companies_financial_data.append(financial_data, ignore_index=True)
    except ValueError:
        print('Data collection interrupted! Continuing rest of the process..')
        
    companies_financial_data = companies_financial_data.loc[:,~companies_financial_data.columns.duplicated()]
    
    return companies_financial_data, companies_profile_data

In [212]:
companies_list = ['AAPL', 'GOOG', 'a34']

df_financial_data, df_profile_data = collect_companies_data(companies_list, api_key)

Data collection interrupted! Continuing rest of the process..

In [171]:
df_financial_data

,date,symbol,fillingDate,acceptedDate,period,revenue,costOfRevenue,grossProfit,grossProfitRatio,researchAndDevelopmentExpenses,...,dividendsPaid,otherFinancingActivites,netCashUsedProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow
0,2019-09-28,AAPL,2019-10-31,2019-10-30 18:12:36,FY,260174000000,161782000000,98392000000,0.378178,16217000000,...,-14119000000,-1936000000,-90976000000,0,24311000000,50224000000,25913000000,69391000000,10495000000,58896000000
1,2018-09-29,AAPL,2018-11-05,2018-11-05 08:01:40,FY,265595000000,163756000000,101839000000,0.383437,14236000000,...,-13712000000,4405000000,-87876000000,0,5624000000,25913000000,20289000000,77434000000,13313000000,64121000000
2,2017-09-30,AAPL,2017-11-03,2017-11-03 08:01:37,FY,229234000000,141048000000,88186000000,0.384699,11581000000,...,-12769000000,31267000000,-17347000000,0,-195000000,20289000000,20484000000,63598000000,12795000000,50803000000
3,2016-09-24,AAPL,2016-10-26,2016-10-26 16:42:16,FY,215639000000,131376000000,84263000000,0.390760,10045000000,...,-12150000000,23394000000,-20483000000,0,-636000000,20484000000,21120000000,65824000000,13548000000,52276000000
4,2015-09-26,AAPL,2015-10-28,2015-10-28 16:31:09,FY,233715000000,140089000000,93626000000,0.400599,8067000000,...,-11561000000,28555000000,-17716000000,0,7276000000,21120000000,13844000000,81266000000,11488000000,69778000000
5,2014-09-27,AAPL,2014-10-27,2014-10-27 17:11:55,FY,182795000000,112258000000,70537000000,0.385880,6041000000,...,-11126000000,17847000000,-37549000000,0,-415000000,13844000000,14259000000,59713000000,9813000000,49900000000
6,2013-09-28,AAPL,2013-10-30,2013-10-29 20:38:28,FY,170910000000,106606000000,64304000000,0.376245,4475000000,...,-10564000000,16515000000,-16379000000,0,3513000000,14259000000,10746000000,53666000000,9076000000,44590000000
7,2012-09-29,AAPL,2012-10-31,2012-10-31 17:07:19,FY,156508000000,87846000000,68662000000,0.438712,3381000000,...,-2488000000,10871000000,-1698000000,0,931000000,10746000000,9815000000,50856000000,9402000000,41454000000
8,2011-09-24,AAPL,2011-10-26,2011-10-26 16:35:25,FY,108249000000,64431000000,43818000000,0.404789,2429000000,...,0,10428000000,1444000000,0,-1446000000,9815000000,11261000000,37529000000,7452000000,30077000000
9,2010-09-25,AAPL,2010-10-27,2010-10-27 16:36:21,FY,65225000000,39541000000,25684000000,0.393775,1782000000,...,0,11606000000,1257000000,0,5998000000,11261000000,5263000000,18595000000,2121000000,16474000000
10,2009-09-26,AAPL,2009-10-27,2009-10-27 16:18:29,FY,36537000000,23397000000,13140000000,0.359635,1333000000,...,0,0,663000000,0,-6612000000,5263000000,11875000000,10159000000,1144000000,9015000000
11,2008-09-27,AAPL,2008-11-05,2008-11-05 06:16:23,FY,32479000000,21334000000,11145000000,0.343145,1109000000,...,0,0,1116000000,0,2523000000,11875000000,9352000000,9596000000,1091000000,8505000000
12,2007-09-29,AAPL,2007-11-15,2007-11-15 16:49:37,FY,24006000000,15852000000,8154000000,0.339665,782000000,...,0,0,739000000,0,2960000000,9352000000,6392000000,5470000000,735000000,4735000000
13,2006-09-30,AAPL,2006-12-29,2006-12-29 06:05:58,FY,13931000000,9888000000,4043000000,0.290216,534000000,...,0,0,324000000,0,2901000000,6392000000,3491000000,2220000000,657000000,1563000000
14,2005-09-24,AAPL,2005-12-01,2005-11-30 21:22:48,FY,13931000000,9888000000,4043000000,0.290216,534000000,...,0,0,543000000,0,522000000,3491000000,2969000000,2535000000,260000000,2275000000
15,2004-09-25,AAPL,2004-12-03,2004-12-02 18:05:49,FY,8279000000,6020000000,2259000000,0.272859,489000000,...,0,0,127000000,0,-427000000,2969000000,3396000000,934000000,176000000,758000000
16,2003-09-27,AAPL,2003-12-19,2003-12-19 17:25:45,FY,6207000000,4499000000,1708000000,0.275173,471000000,...,0,0,27000000,0,1144000000,3396000000,2252000000,289000000,164000000,125000000
17,2002-09-28,AAPL,2002-12-19,2002-12-19 17:20:21,FY,5742000000,4139000000,1603000000,0.279171,446000000,...,0,0,105000000,0,-58000000,2252000000,2310000000,89000000,174000000,-85000000
18,2001-09-29,AAPL,2001-12-21,2001-12-21 00:00:00,FY,5363000000,4128000000,1235000000,0.230282,430000000,...,0,0,42000000,0,1119000000,2310000000,1191000000,185000000,232000000,-47000000
19,2019-12-31,GOOG,2020-02-04,2020-02-03 21:03:59,FY,161857000000,71896000000,89961000000,0.555805,26018000000,...,0,-4228000000,-23209000000,-23000000,1797000000,18498000000,16701000000,54520000000,23548000000,30972000000
20,2018-12-31,GOOG,2019-02-05,2019-02-04 21:06:38,FY,136819000000,59549000000,77270000000,0.564761,21419000000,...,0,2723000000,-13179000000,-302000000,5986000000,16701000000,10715000000,47971000000,25139000000,22832000000
21,2017-12-31,GOOG,2018-02-06,2018-02-05 20:46:29,FY,110855000000,45583000000,65272000000,0.588805,16625000000,...,0,925000000,-8298000000,405000000,-2203000000,10715000000,12918000000,37091000000,13184000000,23907000000
22,2016-12-31,GOOG,2017-02-03,2017-02-02 18:13:47,FY,90272000000,35138000000,55134000000,0.610754,13948000000,...,0,5425000000,-8332000000,-170000000,-3631000000,12918000000,16549000000,36036000000,10212000000,25824000000
23,2015-12-31,GOOG,2016-02-11,2016-02-11 16:38:35,FY,74989000000,28164000000,46825000000,0.624425,12282000000,...,-47000000,11878000000,-3677000000,-434000000,-1798000000,16549000000,18347000000,26024000000,9915000000,16109000000

In [174]:
df_profile_data

,symbol,price,beta,volAvg,mktCap,lastDiv,range,changes,companyName,exchange,...,country,fullTimeEmployees,phone,address,city,state,zip,dcfDiff,dcf,image
0,AAPL,444.45,1.228499,36302764,1900303880000,3.18,199.15-457.65,-10.34,Apple Inc.,Nasdaq Global Select,...,United States,137000,408-996-1010,One Apple Park Way,One Apple Park Way,CA,95014,89.92,297.11,https://financialmodelingprep.com/image-stock/...
1,GOOG,1494.49,1.022765,1685989,1018172080000,0.00,1013.536-1586.99,-5.61,Alphabet Inc.,Nasdaq Global Select,...,United States,123048,650-253-0000,1600 Amphitheatre Parkway,1600 Amphitheatre Parkway,CA,94043,376.88,1641.53,https://financialmodelingprep.com/image-stock/...

In [175]:
df_financial_data.shape, df_profile_data.shape

((24, 99), (2, 26))

In [176]:
def save_data(df, database_filename, table_name):
    """
    This function aims to save a dataset into a sqlite database with the provided name.

    :param df: a dataframe that consists of disaster messages and corresponding categories
    :type df: pd.DataFrame
    :param database_filename: name of the sqlite database
    :type database_filename: str
    :param table_name: name of the SQL table
    :type table_name: str
    :return: none
    """

    engine = create_engine('sqlite:///{}'.format(database_filename))
    df.to_sql(table_name, engine, index=False, if_exists='replace')

In [177]:
database_filepath = './data/CompanyData.db'
save_data(df_financial_data, database_filepath, 'FinancialStatementsTable')
save_data(df_profile_data, database_filepath, 'CompanyProfileTable')

# Get symbol list

get all avaliable companies in financialmodelingprep.com

In [28]:
# get request for symbol list
symbol_list_response = requests.get("https://financialmodelingprep.com/api/v3/stock/list?apikey=08f03438c8b31a22e58ce3ec9f6dabf6")

In [37]:
# convert symbol list to dataframe
symbol_list = symbol_list_response.json()
df_symbols = pd.DataFrame(symbol_list)
df_symbols.head()

,symbol,name,price,exchange
0,SPY,SPDR S&P 500,334.57,NYSE Arca
1,CMCSA,Comcast Corporation Class A Common Stock,42.81,Nasdaq Global Select
2,KMI,Kinder Morgan Inc.,14.32,New York Stock Exchange
3,INTC,Intel Corporation,48.03,Nasdaq Global Select
4,MU,Micron Technology Inc.,48.75,Nasdaq Global Select

In [40]:
# check number of elements in df_symbols
df_symbols.shape

(14369, 4)

In [43]:
# check the number of companies in each stock exchange
df_symbols.exchange.value_counts()

New York Stock Exchange    2602
NYSE Arca                  1540
Nasdaq                     1537
Nasdaq Global Select       1504
Toronto                    1197
NASDAQ Capital Market       878
Paris                       858
NASDAQ Global Market        847
NasdaqGS                    587
NYSE                        457
NasdaqCM                    404
NYSE American               353
NYSEArca                    339
BATS Exchange               258
YHD                         255
Brussels                    165
NasdaqGM                    159
BATS                        144
Amsterdam                   133
Lisbon                       51
Other OTC                    11
MCX                           8
Swiss                         1
Name: exchange, dtype: int64

# Get data of all S&P 500 companies

In [178]:
def load_existing_data(database_filepath):
    """
    This functions aims to load and return the FinancialStatementTable and CompanyProfileTable saved in the database
    given in database_filepath as 2 separate dataframes. If the given database or the tables do not exist,
    this function will return empty dataframes.

    :param database_filepath: file path with the name of the sql database to access
    :type database_filepath: str
    :return: FinancialStatementsTable and CompanyProfile as dataframes, empty dataframes if they do not exist
    :rtype: pd.DataFrame
    """
    df_financial_statements = pd.DataFrame()
    df_profile = pd.DataFrame()


    try:
        engine = create_engine('sqlite:///{}'.format(database_filepath))
    except:
        print('    CompanyData.db does not exist')

    try:
        df_financial_statements = pd.read_sql_table('FinancialStatementsTable', engine)
    except:
        print('    FinancialStatementsTable does not exist in CompanyData.db')

    try:
        df_profile = pd.read_sql_table('CompanyProfileTable', engine)
    except:
        print('    CompanyProfileTable does not exist in CompanyData.db')

    return df_financial_statements, df_profile

In [179]:
df_financial_statements, df_profile = load_existing_data('./data/CompanyData.db')

In [181]:
def compare_lists(list1, list2):
    """
    This function aims to list out all the mismatched elements in two lists.
    
    """
    missing_elements = []
    count = 0
    
    if len(list1) > len(list2):
        for ele in list1:
            if(ele not in list2):
                missing_elements.append(ele)
    else:
        for ele in list2:
            if(ele not in list1):
                missing_elements.append(ele)            
            
    return missing_elements

In [182]:
# check if there are any mismtached elements between the data before and after saving data to sql
compare_lists(df_financial_statements.columns.tolist(), df_financial_data.columns.tolist())

[]

In [184]:
# see if the number of columns in the dataframes before and after saving data to sql is the same
len(df_financial_statements.columns), len(df_financial_data.columns)

(99, 99)

In [280]:
# load S&P 500 data from barchart.com downloaded on 08.08.2020
companies = pd.read_csv('./data/sp-500-index.csv', header=None).iloc[:,0].unique()
companies_list = companies.tolist()
companies_list

['A',
 'AAL',
 'AAP',
 'AAPL',
 'ABBV',
 'ABC',
 'ABMD',
 'ABT',
 'ACN',
 'ADBE',
 'ADI',
 'ADM',
 'ADP',
 'ADSK',
 'AEE',
 'AEP',
 'AES',
 'AFL',
 'AIG',
 'AIV',
 'AIZ',
 'AJG',
 'AKAM',
 'ALB',
 'ALGN',
 'ALK',
 'ALL',
 'ALLE',
 'ALXN',
 'AMAT',
 'AMCR',
 'AMD',
 'AME',
 'AMGN',
 'AMP',
 'AMT',
 'AMZN',
 'ANET',
 'ANSS',
 'ANTM',
 'AON',
 'AOS',
 'APA',
 'APD',
 'APH',
 'APTV',
 'ARE',
 'ATO',
 'ATVI',
 'AVB',
 'AVGO',
 'AVY',
 'AWK',
 'AXP',
 'AZO',
 'BA',
 'BAC',
 'BAX',
 'BBY',
 'BDX',
 'BEN',
 'BF.B',
 'BIIB',
 'BIO',
 'BK',
 'BKNG',
 'BKR',
 'BLK',
 'BLL',
 'BMY',
 'BR',
 'BRK.B',
 'BSX',
 'BWA',
 'BXP',
 'C',
 'CAG',
 'CAH',
 'CARR',
 'CAT',
 'CB',
 'CBOE',
 'CBRE',
 'CCI',
 'CCL',
 'CDNS',
 'CDW',
 'CE',
 'CERN',
 'CF',
 'CFG',
 'CHD',
 'CHRW',
 'CHTR',
 'CI',
 'CINF',
 'CL',
 'CLX',
 'CMA',
 'CMCSA',
 'CME',
 'CMG',
 'CMI',
 'CMS',
 'CNC',
 'CNP',
 'COF',
 'COG',
 'COO',
 'COP',
 'COST',
 'COTY',
 'CPB',
 'CPRT',
 'CRM',
 'CSCO',
 'CSX',
 'CTAS',
 'CTL',
 'CTSH',
 'CTVA',
 'CTXS',
 'CVS',
 'CVX',
 'CXO',
 'D',
 'DAL',
 'DD',
 'DE',
 'DFS',
 'DG',
 'DGX',
 'DHI',
 'DHR',
 'DIS',
 'DISCA',
 'DISCK',
 'DISH',
 'DLR',
 'DLTR',
 'DOV',
 'DOW',
 'DPZ',
 'DRE',
 'DRI',
 'DTE',
 'DUK',
 'DVA',
 'DVN',
 'DXC',
 'DXCM',
 'EA',
 'EBAY',
 'ECL',
 'ED',
 'EFX',
 'EIX',
 'EL',
 'EMN',
 'EMR',
 'EOG',
 'EQIX',
 'EQR',
 'ES',
 'ESS',
 'ETFC',
 'ETN',
 'ETR',
 'EVRG',
 'EW',
 'EXC',
 'EXPD',
 'EXPE',
 'EXR',
 'F',
 'FANG',
 'FAST',
 'FB',
 'FBHS',
 'FCX',
 'FDX',
 'FE',
 'FFIV',
 'FIS',
 'FISV',
 'FITB',
 'FLIR',
 'FLS',
 'FLT',
 'FMC',
 'FOX',
 'FOXA',
 'FRC',
 'FRT',
 'FTI',
 'FTNT',
 'FTV',
 'GD',
 'GE',
 'GILD',
 'GIS',
 'GL',
 'GLW',
 'GM',
 'GOOG',
 'GOOGL',
 'GPC',
 'GPN',
 'GPS',
 'GRMN',
 'GS',
 'GWW',
 'HAL',
 'HAS',
 'HBAN',
 'HBI',
 'HCA',
 'HD',
 'HES',
 'HFC',
 'HIG',
 'HII',
 'HLT',
 'HOLX',
 'HON',
 'HPE',
 'HPQ',
 'HRB',
 'HRL',
 'HSIC',
 'HST',
 'HSY',
 'HUM',
 'HWM',
 'IBM',
 'ICE',
 'IDXX',
 'IEX',
 'IFF',
 'ILMN',
 'INCY',
 'INFO',
 'INTC',
 'INTU',
 'IP',
 'IPG',
 'IPGP',
 'IQV',
 'IR',
 'IRM',
 'ISRG',
 'IT',
 'ITW',
 'IVZ',
 'J',
 'JBHT',
 'JCI',
 'JKHY',
 'JNJ',
 'JNPR',
 'JPM',
 'K',
 'KEY',
 'KEYS',
 'KHC',
 'KIM',
 'KLAC',
 'KMB',
 'KMI',
 'KMX',
 'KO',
 'KR',
 'KSS',
 'KSU',
 'L',
 'LB',
 'LDOS',
 'LEG',
 'LEN',
 'LH',
 'LHX',
 'LIN',
 'LKQ',
 'LLY',
 'LMT',
 'LNC',
 'LNT',
 'LOW',
 'LRCX',
 'LUV',
 'LVS',
 'LW',
 'LYB',
 'LYV',
 'MA',
 'MAA',
 'MAR',
 'MAS',
 'MCD',
 'MCHP',
 'MCK',
 'MCO',
 'MDLZ',
 'MDT',
 'MET',
 'MGM',
 'MHK',
 'MKC',
 'MKTX',
 'MLM',
 'MMC',
 'MMM',
 'MNST',
 'MO',
 'MOS',
 'MPC',
 'MRK',
 'MRO',
 'MS',
 'MSCI',
 'MSFT',
 'MSI',
 'MTB',
 'MTD',
 'MU',
 'MXIM',
 'MYL',
 'NBL',
 'NCLH',
 'NDAQ',
 'NEE',
 'NEM',
 'NFLX',
 'NI',
 'NKE',
 'NLOK',
 'NLSN',
 'NOC',
 'NOV',
 'NOW',
 'NRG',
 'NSC',
 'NTAP',
 'NTRS',
 'NUE',
 'NVDA',
 'NVR',
 'NWL',
 'NWS',
 'NWSA',
 'O',
 'ODFL',
 'OKE',
 'OMC',
 'ORCL',
 'ORLY',
 'OTIS',
 'OXY',
 'OXY.W',
 'PAYC',
 'PAYX',
 'PBCT',
 'PCAR',
 'PEAK',
 'PEG',
 'PEP',
 'PFE',
 'PFG',
 'PG',
 'PGR',
 'PH',
 'PHM',
 'PKG',
 'PKI',
 'PLD',
 'PM',
 'PNC',
 'PNR',
 'PNW',
 'PPG',
 'PPL',
 'PRGO',
 'PRU',
 'PSA',
 'PSX',
 'PVH',
 'PWR',
 'PXD',
 'PYPL',
 'QCOM',
 'QRVO',
 'RCL',
 'RE',
 'REG',
 'REGN',
 'RF',
 'RHI',
 'RJF',
 'RL',
 'RMD',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RSG',
 'RTX',
 'SBAC',
 'SBUX',
 'SCHW',
 'SEE',
 'SHW',
 'SIVB',
 'SJM',
 'SLB',
 'SLG',
 'SNA',
 'SNPS',
 'SO',
 'SPG',
 'SPGI',
 'SRE',
 'STE',
 'STT',
 'STX',
 'STZ',
 'SWK',
 'SWKS',
 'SYF',
 'SYK',
 'SYY',
 'T',
 'TAP',
 'TDG',
 'TDY',
 'TEL',
 'TFC',
 'TFX',
 'TGT',
 'TIF',
 'TJX',
 'TMO',
 'TMUS',
 'TPR',
 'TROW',
 'TRV',
 'TSCO',
 'TSN',
 'TT',
 'TTWO',
 'TWTR',
 'TXN',
 'TXT',
 'TYL',
 'UA',
 'UAA',
 'UAL',
 'UDR',
 'UHS',
 'ULTA',
 'UNH',
 'UNM',
 'UNP',
 'UPS',
 'URI',
 'USB',
 'V',
 'VAR',
 'VFC',
 'VIAC',
 'VLO',
 'VMC',
 'VNO',
 'VRSK',
 'VRSN',
 'VRTX',
 'VTR',
 'VZ',
 'WAB',
 'WAT',
 'WBA',
 'WDC',
 'WEC',
 'WELL',
 'WFC',
 'WHR',
 'WLTW',
 'WM',
 'WMB',
 'WMT',
 'WRB',
 'WRK',
 'WST',
 'WU',
 'WY',
 'WYNN',
 'XEL',
 'XLNX',
 'XOM',
 'XRAY',
 'XRX',
 'XYL',
 'YUM',
 'ZBH',
 'ZBRA',
 'ZION',
 'ZTS']

In [275]:
#test
companies_list = ['AAPL', 'GOOG', 'FB', 'AMZN']

def update_database(companies_list, database_filepath, api_key):
    """
    This function aims to update the given database with the financial and profile data of the selected companies
    in companies_list from financialmodelingprep.com. If the companies' data already exist in the given database,
    the corresponding data will not be retrieved.

    :param companies_list: list of companies whose data should be retrieved from financialmodelingprep.com
    :type companies_list: list
    :param database_filepath: path to the sqlite database
    :type database_filepath: str
    :param api_key: user's api key in financialmodelingprep.com
    :type api_key: str
    :return: none
    """

    missing_companies_list = []

    # load companies' financial statements and profile data dataframes from the given database
    print('    Loading database...')
    df_financial_statements, df_profile = load_existing_data(database_filepath)

    # if no data exists in the database at all, collect data for all companies in companies_list
    if df_financial_statements.empty | df_profile.empty:
        print('    Tables are empty. Getting data from all companies...')
        df_financial_statements, df_profile = collect_companies_data(companies_list, api_key)

        # saving the updated financial statements and profile dataframes to the database
        save_data(df_financial_statements, database_filepath, 'FinancialStatementsTable')
        save_data(df_profile, database_filepath, 'CompanyProfileTable')
        print('    Tables updated!')
    # if some data exists in the database already, select only the missing ones
    else:
        # select the missing companies' symbols from companies_list.
        for symbol in companies_list:
            if symbol not in df_profile.symbol.tolist():
                missing_companies_list.append(symbol)

        if not missing_companies_list:
            print('    No new company to be added to database. Tables are up-to-date!')
        else:
            # update the missing companies' financial statements and profile dataframes
            print('    Tables are out-of-date. Getting data from all companies...')
            new_financial_statements, new_profile = collect_companies_data(missing_companies_list, api_key)
            df_financial_statements = df_financial_statements.append(new_financial_statements, ignore_index=True)
            df_profile = df_profile.append(new_profile, ignore_index=True)

            # saving the updated financial statements and profile dataframes to the database
            save_data(df_financial_statements, database_filepath, 'FinancialStatementsTable')
            save_data(df_profile, database_filepath, 'CompanyProfileTable')
            print('    Tables updated!')

In [276]:
update_database(companies_list, database_filepath, api_key)

    Loading database...
    No new company to be added to database. Tables are up-to-date!

In [281]:
new_financial_statements, new_profile = load_existing_data('./data/CompanyData.db')

In [282]:
new_financial_statements

,date,symbol,fillingDate,acceptedDate,period,revenue,costOfRevenue,grossProfit,grossProfitRatio,researchAndDevelopmentExpenses,...,dividendsPaid,otherFinancingActivites,netCashUsedProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow
0,2019-09-28,AAPL,2019-10-31,2019-10-30 18:12:36,FY,2.601740e+11,1.617820e+11,9.839200e+10,0.378178,1.621700e+10,...,-1.411900e+10,-1.936000e+09,-9.097600e+10,0.0,2.431100e+10,5.022400e+10,2.591300e+10,6.939100e+10,1.049500e+10,5.889600e+10
1,2018-09-29,AAPL,2018-11-05,2018-11-05 08:01:40,FY,2.655950e+11,1.637560e+11,1.018390e+11,0.383437,1.423600e+10,...,-1.371200e+10,4.405000e+09,-8.787600e+10,0.0,5.624000e+09,2.591300e+10,2.028900e+10,7.743400e+10,1.331300e+10,6.412100e+10
2,2017-09-30,AAPL,2017-11-03,2017-11-03 08:01:37,FY,2.292340e+11,1.410480e+11,8.818600e+10,0.384699,1.158100e+10,...,-1.276900e+10,3.126700e+10,-1.734700e+10,0.0,-1.950000e+08,2.028900e+10,2.048400e+10,6.359800e+10,1.279500e+10,5.080300e+10
3,2016-09-24,AAPL,2016-10-26,2016-10-26 16:42:16,FY,2.156390e+11,1.313760e+11,8.426300e+10,0.390760,1.004500e+10,...,-1.215000e+10,2.339400e+10,-2.048300e+10,0.0,-6.360000e+08,2.048400e+10,2.112000e+10,6.582400e+10,1.354800e+10,5.227600e+10
4,2015-09-26,AAPL,2015-10-28,2015-10-28 16:31:09,FY,2.337150e+11,1.400890e+11,9.362600e+10,0.400599,8.067000e+09,...,-1.156100e+10,2.855500e+10,-1.771600e+10,0.0,7.276000e+09,2.112000e+10,1.384400e+10,8.126600e+10,1.148800e+10,6.977800e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,2005-12-31,ALXN,2006-03-07,2006-03-07 16:33:54,FY,6.640000e+05,0.000000e+00,6.640000e+05,1.000000,4.823800e+07,...,0.000000e+00,0.000000e+00,6.761000e+07,0.0,0.000000e+00,4.362900e+07,4.695100e+07,-5.036500e+07,4.440000e+05,-5.080900e+07
525,2005-07-31,ALXN,2005-10-11,2005-10-11 16:12:49,FY,1.064000e+06,0.000000e+00,1.064000e+06,1.000000,9.138800e+07,...,0.000000e+00,0.000000e+00,2.898500e+07,0.0,0.000000e+00,4.695100e+07,1.132240e+08,-9.688300e+07,2.980000e+06,-9.986300e+07
526,2004-07-31,ALXN,2004-09-28,2004-09-27 18:06:59,FY,4.609000e+06,0.000000e+00,4.609000e+06,1.000000,5.984000e+07,...,0.000000e+00,0.000000e+00,1.272230e+08,0.0,8.838000e+07,1.132240e+08,2.484400e+07,-7.199300e+07,3.135000e+06,-7.512800e+07
527,2003-07-31,ALXN,2003-10-27,2003-10-27 17:11:25,FY,8.770000e+05,0.000000e+00,8.770000e+05,1.000000,7.104200e+07,...,0.000000e+00,0.000000e+00,1.550000e+05,0.0,-2.273000e+07,2.484400e+07,4.757400e+07,-8.919600e+07,3.070000e+06,-9.226600e+07
528,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [283]:
new_profile

,symbol,price,beta,volAvg,mktCap,lastDiv,range,changes,companyName,exchange,...,country,fullTimeEmployees,phone,address,city,state,zip,dcfDiff,dcf,image
0,AAPL,444.45,1.228499,36302764,1900303880000,3.180,199.15-457.65,-10.34,Apple Inc.,Nasdaq Global Select,...,United States,137000,408-996-1010,One Apple Park Way,One Apple Park Way,CA,95014,89.92,297.11,https://financialmodelingprep.com/image-stock/...
1,GOOG,1494.49,1.022765,1685989,1018172080000,0.000,1013.536-1586.99,-5.61,Alphabet Inc.,Nasdaq Global Select,...,United States,123048,650-253-0000,1600 Amphitheatre Parkway,1600 Amphitheatre Parkway,CA,94043,376.88,1641.53,https://financialmodelingprep.com/image-stock/...
2,FB,268.44,1.062394,25607320,764737220000,0.000,137.1-278.89,3.16,Facebook Inc.,Nasdaq Global Select,...,United States,48268,650-543-4800,1601 Willow Road,1601 Willow Road,CA,94025,542.33,736.82,https://financialmodelingprep.com/image-stock/...
3,AMZN,3167.46,1.516863,4611025,1586548970000,0.000,1626.03-3344.29,-57.54,Amazon.com Inc.,Nasdaq Global Select,...,United States,840400,206-266-1000,410 Terry Avenue North,410 Terry Avenue North,WA,98109-5210,-1002.74,898.53,https://financialmodelingprep.com/image-stock/...
4,DIS,129.93,1.024451,15539996,234791289000,1.760,79.07-153.41,-0.89,The Walt Disney Company,New York Stock Exchange,...,None,None,None,None,None,None,None,27.69,162.50,https://financialmodelingprep.com/image-stock/...
5,A,97.78,1.424957,1799737,30192214000,0.704,61.13-99.36,0.33,Agilent Technologies Inc.,New York Stock Exchange,...,United States,16370,800 227 9770,5301 Stevens Creek Boulevard,5301 Stevens Creek Boulevard,CA,95051,-53.50,22.67,https://financialmodelingprep.com/image-stock/...
6,AAL,13.03,1.643338,95033567,6626549800,0.400,8.25-31.67,-0.01,American Airlines Group Inc.,Nasdaq Global Select,...,United States,131500,817 963 1234,1 Skyview Drive,1 Skyview Drive,TX,76155,193.71,227.09,https://financialmodelingprep.com/image-stock/...
7,AAP,151.97,0.832209,956179,10501309400,0.870,71.33-171.43,0.14,Advance Auto Parts Inc W/I,New York Stock Exchange,...,United States,39000,540 362 4911,2635 East Millbrook Road,2635 East Millbrook Road,NC,27604,NaN,0.00,https://financialmodelingprep.com/image-stock/...
8,ABBV,92.92,0.952782,9015957,163987997000,5.680,62.55-101.28,0.35,AbbVie Inc.,New York Stock Exchange,...,United States,30000,847 932 7900,1 North Waukegan Road,1 North Waukegan Road,IL,60064,45.83,123.83,https://financialmodelingprep.com/image-stock/...
9,ABC,102.10,0.972175,1180064,20842897400,1.640,72.06-106.45,0.49,AmerisourceBergen Corporation,New York Stock Exchange,...,United States,21000,610-727-7000,1300 Morris Drive,1300 Morris Drive,PA,19087,60.11,134.22,https://financialmodelingprep.com/image-stock/...
10,ABMD,310.82,0.324620,438675,14000607200,0.000,119.01-319.19,-4.16,ABIOMED Inc.,Nasdaq Global Select,...,United States,1536,978 646 1400,22 Cherry Hill Drive,22 Cherry Hill Drive,MA,01923,975.98,1246.88,https://financialmodelingprep.com/image-stock/...
11,ABT,101.23,1.112141,5905871,179230769000,1.400,61.61-102.89,-0.52,Abbott Laboratories,New York Stock Exchange,...,United States,107000,224 667 6100,100 Abbott Park Road,100 Abbott Park Road,IL,60064,-30.72,30.36,https://financialmodelingprep.com/image-stock/...
12,ACN,231.56,1.036256,2059560,147526189000,3.200,137.15-231.87,0.67,Accenture plc Class A (Ireland),New York Stock Exchange,...,Ireland,509000,353 1 646 2000,1 Grand Canal Square,1 Grand Canal Square,None,2,NaN,0.00,https://financialmodelingprep.com/image-stock/...
13,ADBE,449.57,1.101180,2834482,215642997000,0.000,255.13-470.61,-14.54,Adobe Systems Incorporated,Nasdaq Global Select,...,United States,22634,408-536-6000,345 Park Avenue,345 Park Avenue,CA,95110,-205.33,70.17,https://financialmodelingprep.com/image-stock/...
14,ADI,116.32,1.408094,2927875,42916729000,2.320,79.08-127.39,-0.42,Analog Devices Inc.,Nasdaq Global Select,...,United States,16400,781-329-4700,One Technology Way,One Technology Way,MA,02062,-93.11,0.00,https://financialmodelingprep.com/image-stock/...
15,ADM,44.03,1.077571,2722029,24465135600,1.420,28.92-47.2,0.48,Archer-Daniels-Midland Company,New York Stock Exchange,...,United States,38000,312 634 8100,77 West Wacker Drive,77 West Wacker Drive,IL,60601,NaN,0.00,https://financialmodelingprep.com/image-stock/...
16,ADP,137.99,0.881112,2249775,59330871000,3.520,103.11-182.32,1.47,Automatic Data Processing Inc.,Nasdaq Global Select,...,United States,58000,973-974-5000,One ADP Boulevard,One ADP Boulevard,NJ,07068,-80.04,82.70,https://financialmodelingprep.com/image-stock/...
17,ADSK,236.24,1.890387,1470865,51783098000,0.000,125.38-251.39,-7.33,Autodesk Inc.,Nasdaq Global Select,...,United States,10100,415 507 5000,111 McInnis Parkway,111 McInnis Parkway,CA,94903,NaN,0.00,https://financialmodelingprep.com/image-stock/...
18,AEE,82.18,0.198145,1753239,20289503200,1.960,58.74-87.66,1.12,Ameren Corporation,New York Stock Exchange,...,United States,9323,314-621-3222,1901 Chouteau Avenue,1901 Chouteau Avenue,MO,63103,NaN,0.00,https://financialmodelingprep.com/image-stock/...
19,AEP,86.60,0.070826,3157143,42917487000,2.800,65.14-104.97,1.93,American Electric Power Company Inc.,New York Stock Exchange,...,United States,17408,614-716-1000,1 Riverside Plaza,1 Riverside Plaza,OH,43215-2373,3627.74,3711.87,https://financialmodelingprep.com/image-stock/...
20,AES,17.16,1.075042,6635564,11409804300,0.566,8.11-21.23,0.61,The AES Corporation,New York Stock Exchange,...,United States,8000,703-522-1315,4300 Wilson Boulevard,4300 Wilson Boulevard,VA,22203,NaN,0.00,https://financialmodelingprep.com/image-stock/...
21,AFL,36.52,0.714165,3904676,26035546100,1.100,23.07-55.07,1.11,AFLAC Incorporated,New York Stock Exchange,...,United States,11729,706-323-3431,1932 Wynnton Road,1932 Wynnton Road,GA,31999,NaN,0.00,https://financialmodelingprep.com/image-stock/...
22,AIG,30.66,1.187183,6830145,26411565100,1.280,16.07-58.66,1.34,American International Group Inc.,New York Stock Exchange,...,United States,46000,212-770-7000,175 Water Street,175 Water Street,NY,10038,-45.04,0.00,https://financialmodelingprep.com/image-stock/...
23,AIV,37.03,0.490725,1226132,5512470500,1.600,24.53-55.68,0.03,Apartment Investment and Management Company,New York Stock Exchange,...,United States,950,303-757-8101,4582 South Ulster Street,4582 South Ulster Street,CO,80237,NaN,0.00,https://financialmodelingprep.com/image-stock/...
24,AIZ,122.21,0.491568,495787,7290107400,2.490,76.27-142.61,3.34,Assurant Inc.,New York Stock Exchange,...,United States,14000,212-859-7000,28 Liberty Street,28 Liberty Street,NY,10005,NaN,0.00,https://financialmodelingprep.com/image-stock/...
25,AJG,106.81,0.805227,1064082,20450801700,1.760,65.09-109.46,1.25,Arthur J. Gallagher & Co.,New York Stock Exchange,...,United States,34000,630-773-3800,2850 Golf Road,2850 Golf Road,IL,60008,NaN,0.00,https://financialmodelingprep.com/image-stock/...
26,AKAM,109.22,0.583473,1869512,17802860500,0.000,75.18-116.39,0.04,Akamai Technologies Inc.,Nasdaq Global Select,...,United States,7742,617-444-3000,145 Broadway,145 Broadway,MA,02142,NaN,0.00,https://financialmodelingprep.com/image-stock/...
27,ALB,84.44,1.651770,1284409,8980870100,1.506,48.89-99.4,1.10,Albemarle Corporation,New York Stock Exchange,...,United States,6000,980-299-5700,4250 Congress Street,4250 Congress Street,NC,28209,-2.63,74.15,https://financialmodelingprep.com/image-stock/...
28,ALGN,305.81,2.067453,965581,24093761500,0.000,127.88-326.36,4.01,Align Technology Inc.,Nasdaq Global Select,...,United States,14530,408 470 1000,2820 Orchard Parkway,2820 Orchard Parkway,CA,95134,NaN,0.00,https://financialmodelingprep.com/image-stock/...
29,ALK,36.61,0.785834,3509675,4526460400,1.425,20.02-72.22,0.19,Alaska Air Group Inc.,New York Stock Exchange,...,United States,22473,206 392 5040,19300 International Boulevard,19300 International Boulevard,WA,98188,403.41,464.22,https://financialmodelingprep.com/image-stock/...
30,ALL,96.91,0.818718,2102245,30266544100,2.080,64.13-125.92,2.43,Allstate Corporation (The),New York Stock Exchange,...,United States,45780,847-402-2800,2775 Sanders Road,2775 Sanders Road,IL,60062-6127,NaN,0.00,https://financialmodelingprep.com/image-stock/...
31,ALLE,100.11,1.182967,717010,9233485800,1.180,77.37-139.24,0.91,Allegion plc,New York Stock Exchange,...,Ireland,11000,353 1 254 6200,Iveagh Court,Iveagh Court,None,2,NaN,0.00,https://financialmodelingprep.com/image-stock/...
32,ALXN,103.28,1.672006,1944143,22636185600,0.000,72.67-125.52,-0.62,Alexion Pharmaceuticals Inc.,Nasdaq Global Select,...,United States,3082,475 230 2596,121 Seaport Boulevard,121 Seaport Boulevard,MA,02210,NaN,0.00,https://financialmodelingprep.com/image-stock/...
33,AMAT,63.57,1.653456,7330490,58260570000,0.850,36.64-69.44,-0.04,Applied Materials Inc.,Nasdaq Global Select,...,United States,22700,408-727-5555,3050 Bowers Avenue,3050 Bowers Avenue,CA,95052,5.29,49.86,https://financialmodelingprep.com/image-stock/...